# Generated by Django 4.0.1 on 2022-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
